#!/usr/bin/env python3
from __future__ import annotations
import json
import os
import re
import subprocess
from pathlib import Path
from typing import Iterable
import datetime as dt
import yaml
from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "controls/catalog.yaml"
SCHEMA_PATH = ROOT / "controls/catalog.schema.json"
ARTIFACT_INDEX_PATH = ROOT / "artifact-index.yaml"
GENERATED_DIR = ROOT / "docs/generated"
REPORT_PATH = GENERATED_DIR / "consistency-report.md"

MD_LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
DOC_FILE_RE = re.compile(r"`([^`]+\.md)`")


def shell_ok(path: Path) -> tuple[bool, str]:
    proc = subprocess.run(["bash", "-n", str(path)], capture_output=True, text=True)
    return (proc.returncode == 0, proc.stderr.strip())


def normalize_dates(obj):
    if isinstance(obj, dict):
        return {k: normalize_dates(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [normalize_dates(v) for v in obj]
    if isinstance(obj, (dt.date, dt.datetime)):
        return obj.isoformat()[:10]
    return obj


def load_yaml(path: Path):
    return normalize_dates(yaml.safe_load(path.read_text()))


def check_catalog() -> list[str]:
    errors: list[str] = []
    catalog = load_yaml(CATALOG_PATH)
    schema = json.loads(SCHEMA_PATH.read_text())
    validator = Draft202012Validator(schema)
    for error in validator.iter_errors(catalog):
        errors.append(f"catalog schema: {'/'.join(str(x) for x in error.path)}: {error.message}")
    ids = [c["control_id"] for c in catalog["controls"]]
    if len(ids) != len(set(ids)):
        errors.append("catalog schema: duplicate control_id detected")
    return errors


def check_artifact_index() -> list[str]:
    errors: list[str] = []
    idx = load_yaml(ARTIFACT_INDEX_PATH)
    generated_allowed_missing = {REPORT_PATH.relative_to(ROOT).as_posix()}
    seen = set()
    for artifact in idx["artifacts"]:
        path = artifact["path"]
        if path in seen:
            errors.append(f"artifact index: duplicate path {path}")
        seen.add(path)
        if not (ROOT / path).exists() and path not in generated_allowed_missing:
            errors.append(f"artifact index: missing file {path}")
    return errors


def iter_markdown_files() -> Iterable[Path]:
    for path in ROOT.rglob("*.md"):
        if ".git" not in path.parts:
            yield path


def check_markdown_links() -> list[str]:
    errors: list[str] = []
    for path in iter_markdown_files():
        text = path.read_text()
        for match in MD_LINK_RE.finditer(text):
            target = match.group(1)
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            resolved = (path.parent / target).resolve()
            try:
                resolved.relative_to(ROOT.resolve())
            except ValueError:
                errors.append(f"markdown link: {path.relative_to(ROOT)} -> escapes repo: {target}")
                continue
            if not resolved.exists():
                errors.append(f"markdown link: {path.relative_to(ROOT)} -> missing target {target}")
    return errors


def check_stack_doc_index() -> list[str]:
    errors: list[str] = []
    path = ROOT / "docs/architecture/stack-bom.md"
    allowed_missing = {REPORT_PATH.resolve()}
    text = path.read_text()
    for rel in DOC_FILE_RE.findall(text):
        if rel.startswith("docs/"):
            candidate = ROOT / rel
        else:
            candidate = path.parent / rel
        if not candidate.exists() and candidate.resolve() not in allowed_missing:
            errors.append(f"stack-bom document index: missing reference {rel}")
    return errors


def check_shell_scripts() -> list[str]:
    errors: list[str] = []
    for path in sorted((ROOT / "evidence-pipeline").rglob("*.sh")):
        ok, stderr = shell_ok(path)
        if not ok:
            errors.append(f"shell syntax: {path.relative_to(ROOT)}: {stderr}")
    return errors


def generate_report(errors: list[str]) -> str:
    status = "PASS" if not errors else "FAIL"
    lines = []
    lines.append("# Automated Consistency Report\n")
    lines.append("This file is generated by `scripts/validate_repo.py`.\n")
    lines.append(f"Status: **{status}**\n")
    checks = [
        "control catalog schema and uniqueness",
        "artifact index file existence",
        "local markdown link integrity",
        "stack BOM document index references",
        "shell syntax for evidence scripts",
    ]
    lines.append("## Checks executed")
    for check in checks:
        lines.append(f"- {check}")
    lines.append("")
    if errors:
        lines.append("## Failures")
        for err in errors:
            lines.append(f"- {err}")
    else:
        lines.append("## Result")
        lines.append("- No validation failures detected in the checked surfaces.")
    lines.append("")
    lines.append("## Commands")
    lines.append("```bash")
    lines.append("python3 scripts/render_controls.py")
    lines.append("python3 scripts/validate_repo.py")
    lines.append("```")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    errors = []
    errors.extend(check_catalog())
    errors.extend(check_artifact_index())
    errors.extend(check_markdown_links())
    errors.extend(check_stack_doc_index())
    errors.extend(check_shell_scripts())
    REPORT_PATH.write_text(generate_report(errors))
    if errors:
        for err in errors:
            print(err)
        return 1
    print("validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
